[project]
name = "snp-pipeline"
version = "0.1.0"
description = "Pipeline to clean and map reads"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "xlrd>=2.0.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
